### ISSUE TITLE
How to run this software?

### ISSUE THREAD

**Issue by zhixuqiu** [yinxc/structural-information-minimisation#2]
I want to use your software deDoc. Although the Hi-C matrix was same as the description of readme text for deDoC, there are some strange error when I used it. 
Could you help me about this? I would appreciate is if you can give me a hand!

The error like this:
/home/qiuzx/software/packages_save/deDoc$ java -jar deDoc.jar hictest.matrix 
deDoc(E) begin: 2018-09-02 20:41:04
Exception in thread "main" java.lang.NumberFormatException: For input string: "1	1	536.0"
 at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
 at java.lang.Integer.parseInt(Integer.java:580)
 at java.lang.Integer.parseInt(Integer.java:615)
 at filerw.Tool.GetGraph(Tool.java:27)
 at main.deDoc.dedoc(deDoc.java:26)
 at main.deDoc.main(deDoc.java:17)

**Comment by matthewpendleton** [comment]
You need to have the first line contain the number of entries in the file.

**Comment by matthewpendleton** [comment]
so the head of your file should look like this:

239485724933
1 1 536.0
1 2 18465.0
2 1 18465.0

for a file that contains 239485724933 total entries (which should be equal to the square of the number of bins in the genome at the given resolution minus the number of bins containing zero read support).

**Comment by yinxc** [comment]
the first line is the number of bins in the hic matrix

**Comment by J4X-ZH4NG** [comment]
based on my testing，the first line should be the size(or more than it?) of hic matirx
such as the matrix:
1 3 1.0
1 50 3.0
200 3 1.1

the first line may be 200
